apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: mennidiskind/weather-service-a:v1
          env:
            - name: SERVICE_B_URL
              value: http://service-b:8000/clean
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
    - port: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: service-a
spec:
  to:
    kind: Service
    name: service-a
